package com.jdend.erp.vehicle.advance.service;

import com.jdend.erp.accounting.settings.service.OtherAccountSettingsService;
import com.jdend.erp.accounting.voucher.entity.Voucher;
import com.jdend.erp.accounting.voucher.entity.VoucherLine;
import com.jdend.erp.accounting.voucher.repository.VoucherRepository;
import com.jdend.erp.vehicle.advance.dto.VehicleAdvanceRowDto;
import com.jdend.erp.vehicle.advance.dto.VehicleAdvanceSaveRequest;
import com.jdend.erp.vehicle.advance.entity.VehicleAdvance;
import com.jdend.erp.vehicle.advance.repository.VehicleAdvanceRepository;
import com.jdend.erp.vehicle.entity.VehicleOrder;
import com.jdend.erp.vehicle.repository.VehicleOrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Set;

@Service
@RequiredArgsConstructor
public class VehicleAdvanceService {

  private final VehicleOrderRepository orderRepo;
  private final VehicleAdvanceRepository advanceRepo;
  private final VoucherRepository voucherRepo;
  private final OtherAccountSettingsService accountSettings;

  private static final Set<String> VAT_ZERO_ITEMS = Set.of(
    "취득세", "인지대", "공채할인금액", "공채매입금액"
  );

  private static final String AUTO_VOUCHER_MEMO_PREFIX = "[차량선급자동전표] ";

  @Transactional(readOnly = true)
  public List<VehicleAdvanceRowDto> list(String mgmtNo) {
    VehicleOrder o = orderRepo.findByVehicleMgmtNo(mgmtNo)
      .orElseThrow(() -> new RuntimeException("차량 없음: " + mgmtNo));

    return advanceRepo.findByVehicleOrder_IdOrderByIdAsc(o.getId())
      .stream()
      .map(a -> VehicleAdvanceRowDto.builder()
        .id(a.getId())
        .itemName(a.getItemName())
        .advanceAmount(a.getAdvanceAmount())
        .supplyAmount(a.getSupplyAmount())
        .vatAmount(a.getVatAmount())
        .voucherDate(a.getVoucherDate())
        .paymentMethod(a.getPaymentMethod())
        .remark(a.getRemark())
        .build())
      .toList();
  }

  @Transactional
  public int saveAll(String mgmtNo, VehicleAdvanceSaveRequest req) {
    VehicleOrder o = orderRepo.findByVehicleMgmtNo(mgmtNo)
      .orElseThrow(() -> new RuntimeException("차량 없음: " + mgmtNo));

    advanceRepo.deleteByVehicleOrder_Id(o.getId());
    deleteAutoGeneratedVouchers(mgmtNo);

    long totalAdvance = 0L;
    int voucherCreatedCount = 0;

    if (req != null && req.rows != null) {
      for (VehicleAdvanceRowDto r : req.rows) {
        if (r.itemName == null || r.itemName.isBlank()) continue;

        if (r.paymentMethod == null || r.paymentMethod.isBlank()) {
          throw new RuntimeException("지급방법이 결정되지 않은건이 있습니다.");
        }

        long adv = nvl(r.advanceAmount);
        if (adv <= 0) continue;

        long supply;
        long vat;

        if (VAT_ZERO_ITEMS.contains(r.itemName)) {
          supply = adv;
          vat = 0L;
        } else {
          supply = Math.round(adv / 1.1);
          vat = adv - supply;
        }

        VehicleAdvance savedAdvance = advanceRepo.save(VehicleAdvance.builder()
          .vehicleOrder(o)
          .itemName(r.itemName)
          .advanceAmount(adv)
          .supplyAmount(supply)
          .vatAmount(vat)
          .voucherDate(r.voucherDate)
          .paymentMethod(emptyToNull(r.paymentMethod))
          .remark(emptyToNull(r.remark))
          .build());

        totalAdvance += adv;
        createVoucherForAdvance(o, savedAdvance);
        voucherCreatedCount++;
      }
    }

    o.setTotalAdvancePrice(totalAdvance);
    orderRepo.save(o);

    return voucherCreatedCount;
  }

  /**
   * 선급 전표 발생 규칙
   * - 차변: 항목별 계정 / 선급금액
   * - 대변: 지급방법별 계정 / 선급금액
   * - description:
   *    차변 = 항목명
   *    대변 = 지급방법
   */
  private void createVoucherForAdvance(VehicleOrder order, VehicleAdvance advance) {
    LocalDate voucherDate = advance.getVoucherDate() != null ? advance.getVoucherDate() : LocalDate.now();
    String voucherNo = generateVoucherNo(voucherDate);

    String debitAccount = mapItemNameToDebitAccount(advance.getItemName());
    String creditAccount = mapPaymentMethodToCreditAccount(advance.getPaymentMethod());

    String itemName = nvlStr(advance.getItemName());
    String paymentMethod = nvlStr(advance.getPaymentMethod());
    String vehicleNo = emptyToNull(order.getVehicleNo());
    String memo = AUTO_VOUCHER_MEMO_PREFIX + order.getVehicleMgmtNo() + " / " + itemName;

    long totalAmt = nvl(advance.getAdvanceAmount());
    long supplyAmt = nvl(advance.getSupplyAmount());
    long vatAmt = nvl(advance.getVatAmount());

    Voucher voucher = Voucher.builder()
      .voucherNo(voucherNo)
      .voucherDate(voucherDate)
      .contractNumber(null)
      .vehicleNo(vehicleNo)
      .totalAmount(totalAmt)
      .status("대기")
      .memo(memo)
      .build();

    int sortOrder = 1;

    if (vatAmt > 0) {
      // 과세 항목: 공급가액 + 부가세대급금으로 분개
      voucher.addLine(VoucherLine.builder()
        .lineType("DEBIT")
        .accountName(debitAccount)
        .amount(supplyAmt)
        .description(itemName)
        .sortOrder(sortOrder++)
        .build());

      voucher.addLine(VoucherLine.builder()
        .lineType("DEBIT")
        .accountName("부가세대급금")
        .amount(vatAmt)
        .description(itemName + " 부가세")
        .sortOrder(sortOrder++)
        .build());
    } else {
      // 면세/비과세 항목 (취득세, 인지대 등): 단일 차변
      voucher.addLine(VoucherLine.builder()
        .lineType("DEBIT")
        .accountName(debitAccount)
        .amount(totalAmt)
        .description(itemName)
        .sortOrder(sortOrder++)
        .build());
    }

    voucher.addLine(VoucherLine.builder()
      .lineType("CREDIT")
      .accountName(creditAccount)
      .amount(totalAmt)
      .description(paymentMethod)
      .sortOrder(sortOrder)
      .build());

    voucherRepo.save(voucher);
  }

  private void deleteAutoGeneratedVouchers(String mgmtNo) {
    String memoPrefix = AUTO_VOUCHER_MEMO_PREFIX + mgmtNo;
    List<Voucher> oldVouchers = voucherRepo.findByMemoStartingWithOrderByIdAsc(memoPrefix);
    if (!oldVouchers.isEmpty()) {
      voucherRepo.deleteAll(oldVouchers);
    }
  }

  private String mapItemNameToDebitAccount(String itemName) {
    if (itemName == null || itemName.isBlank()) {
      throw new RuntimeException("항목명이 없습니다.");
    }
    // 기타계정관리 설정에서 항목명에 맞는 계정명 조회
    String fromSettings = accountSettings.getPrepaidDebitAccount(itemName);
    if (fromSettings != null) return fromSettings;
    // 설정에 없으면 기본값
    return "차량운반구";
  }

  private String mapPaymentMethodToCreditAccount(String paymentMethod) {
    if (paymentMethod == null || paymentMethod.isBlank()) {
      throw new RuntimeException("지급방법이 결정되지 않은건이 있습니다.");
    }

    return switch (paymentMethod) {
      case "미지급금" -> "미지급금";
      case "법인카드" -> "미지급비용";
      case "보통예금" -> "보통예금";
      default -> throw new RuntimeException("지원하지 않는 지급방법입니다: " + paymentMethod);
    };
  }

  private String generateVoucherNo(LocalDate voucherDate) {
    long seq = voucherRepo.countByVoucherDate(voucherDate) + 1;
    String baseDate = voucherDate.toString().replace("-", "");

    String voucherNo = "V-" + baseDate + "-" + String.format("%03d", seq);

    while (voucherRepo.existsByVoucherNo(voucherNo)) {
      seq++;
      voucherNo = "V-" + baseDate + "-" + String.format("%03d", seq);
    }

    return voucherNo;
  }

  private long nvl(Long v) {
    return v == null ? 0L : v;
  }

  private String nvlStr(String s) {
    return s == null ? "" : s;
  }

  private String emptyToNull(String s) {
    return (s == null || s.isBlank()) ? null : s;
  }
}