package com.jdend.erp.vehicle.advance.service;

import com.jdend.erp.accounting.settings.service.OtherAccountSettingsService;
import com.jdend.erp.accounting.voucher.entity.Voucher;
import com.jdend.erp.accounting.voucher.entity.VoucherLine;
import com.jdend.erp.accounting.voucher.repository.VoucherRepository;
import com.jdend.erp.accounting.voucher.service.VoucherNumberService;
import com.jdend.erp.vehicle.advance.dto.VehicleAdvanceRowDto;
import com.jdend.erp.vehicle.advance.dto.VehicleAdvanceSaveRequest;
import com.jdend.erp.vehicle.advance.entity.VehicleAdvance;
import com.jdend.erp.vehicle.advance.repository.VehicleAdvanceRepository;
import com.jdend.erp.vehicle.entity.VehicleOrder;
import com.jdend.erp.vehicle.repository.VehicleOrderRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Set;

@Slf4j
@Service
@RequiredArgsConstructor
public class VehicleAdvanceService {

  private final VehicleOrderRepository orderRepo;
  private final VehicleAdvanceRepository advanceRepo;
  private final VoucherRepository voucherRepo;
  private final OtherAccountSettingsService accountSettings;
  private final VoucherNumberService voucherNumberService;

  private static final Set<String> VAT_ZERO_ITEMS = Set.of(
    "취득세", "인지대", "공채할인금액", "공채매입금액"
  );

  private static final String AUTO_VOUCHER_MEMO_PREFIX = "[차량선급자동전표] ";

  @Transactional(readOnly = true)
  public List<VehicleAdvanceRowDto> list(String mgmtNo) {
    // 주의: 발주(미실행) …000 공유값에는 부적합(NonUnique). pre-실행은 listById(id) 사용.
    VehicleOrder o = orderRepo.findByVehicleMgmtNo(mgmtNo)
      .orElseThrow(() -> new RuntimeException("차량 없음: " + mgmtNo));
    return listFor(o);
  }

  // 발주~선급(pre-실행) 단계 조회는 행 PK(id)로 특정(…000 공유 대비).
  @Transactional(readOnly = true)
  public List<VehicleAdvanceRowDto> listById(Long id) {
    VehicleOrder o = orderRepo.findById(id)
      .orElseThrow(() -> new RuntimeException("차량 없음(id): " + id));
    return listFor(o);
  }

  private List<VehicleAdvanceRowDto> listFor(VehicleOrder o) {
    return advanceRepo.findByVehicleOrder_IdOrderByIdAsc(o.getId())
      .stream()
      .map(a -> VehicleAdvanceRowDto.builder()
        .id(a.getId())
        .itemName(a.getItemName())
        .advanceAmount(a.getAdvanceAmount())
        .supplyAmount(a.getSupplyAmount())
        .vatAmount(a.getVatAmount())
        .voucherDate(a.getVoucherDate())
        .paymentMethod(a.getPaymentMethod())
        .remark(a.getRemark())
        .build())
      .toList();
  }

  @Transactional
  public int saveAll(String mgmtNo, VehicleAdvanceSaveRequest req) {
    // 주의: 발주(미실행) …000 공유값에는 부적합(NonUnique). pre-실행은 saveAllById(id) 사용.
    VehicleOrder o = orderRepo.findByVehicleMgmtNo(mgmtNo)
      .orElseThrow(() -> new RuntimeException("차량 없음: " + mgmtNo));
    return saveAllFor(o, req);
  }

  // 발주~선급(pre-실행) 단계 저장은 행 PK(id)로 특정(…000 공유 대비).
  @Transactional
  public int saveAllById(Long id, VehicleAdvanceSaveRequest req) {
    VehicleOrder o = orderRepo.findById(id)
      .orElseThrow(() -> new RuntimeException("차량 없음(id): " + id));
    return saveAllFor(o, req);
  }

  private int saveAllFor(VehicleOrder o, VehicleAdvanceSaveRequest req) {
    advanceRepo.deleteByVehicleOrder_Id(o.getId());
    deleteAutoGeneratedVouchers(o);

    long totalAdvance = 0L;
    int voucherCreatedCount = 0;

    if (req != null && req.rows != null) {
      for (VehicleAdvanceRowDto r : req.rows) {
        if (r.itemName == null || r.itemName.isBlank()) continue;

        if (r.paymentMethod == null || r.paymentMethod.isBlank()) {
          throw new RuntimeException("지급방법이 결정되지 않은건이 있습니다.");
        }

        long adv = nvl(r.advanceAmount);
        if (adv <= 0) continue;

        long supply;
        long vat;

        if (VAT_ZERO_ITEMS.contains(r.itemName)) {
          supply = adv;
          vat = 0L;
        } else {
          supply = Math.round(adv / 1.1);
          vat = adv - supply;
        }

        VehicleAdvance savedAdvance = advanceRepo.save(VehicleAdvance.builder()
          .vehicleOrder(o)
          .itemName(r.itemName)
          .advanceAmount(adv)
          .supplyAmount(supply)
          .vatAmount(vat)
          .voucherDate(r.voucherDate)
          .paymentMethod(emptyToNull(r.paymentMethod))
          .remark(emptyToNull(r.remark))
          .build());

        totalAdvance += adv;
        createVoucherForAdvance(o, savedAdvance);
        voucherCreatedCount++;
      }
    }

    o.setTotalAdvancePrice(totalAdvance);
    orderRepo.save(o);

    return voucherCreatedCount;
  }

  /**
   * 선급 전표 발생 규칙
   * - 차변: 항목별 계정 / 선급금액
   * - 대변: 지급방법별 계정 / 선급금액
   * - description:
   *    차변 = 항목명
   *    대변 = 지급방법
   */
  private void createVoucherForAdvance(VehicleOrder order, VehicleAdvance advance) {
    LocalDate voucherDate = advance.getVoucherDate() != null ? advance.getVoucherDate() : LocalDate.now();
    String voucherNo = generateVoucherNo(voucherDate);

    String debitAccount = mapItemNameToDebitAccount(advance.getItemName());
    String creditAccount = mapPaymentMethodToCreditAccount(advance.getPaymentMethod());

    String itemName = nvlStr(advance.getItemName());
    String paymentMethod = nvlStr(advance.getPaymentMethod());
    String vehicleNo = emptyToNull(order.getVehicleNo());
    String memo = autoVoucherMemoPrefix(order) + " / " + itemName;

    long totalAmt = nvl(advance.getAdvanceAmount());
    long supplyAmt = nvl(advance.getSupplyAmount());
    long vatAmt = nvl(advance.getVatAmount());

    Voucher voucher = Voucher.builder()
      .voucherNo(voucherNo)
      .voucherDate(voucherDate)
      .contractNumber(null)
      .vehicleNo(vehicleNo)
      .vehicleMgmtNo(emptyToNull(order.getVehicleMgmtNo()))
      .totalAmount(totalAmt)
      .status("대기")
      .memo(memo)
      .build();

    int sortOrder = 1;

    if (vatAmt > 0) {
      String vatDebitAccount = accountSettings.getAdvanceVatDebitAccount();
      if (vatDebitAccount != null) {
        // 부가세 계정 설정 시: 공급가액 + 부가세 분리 차변 (합계 = totalAmt = 대변)
        voucher.addLine(VoucherLine.builder()
          .lineType("DEBIT")
          .accountName(debitAccount)
          .amount(supplyAmt)
          .description(itemName)
          .sortOrder(sortOrder++)
          .build());
        voucher.addLine(VoucherLine.builder()
          .lineType("DEBIT")
          .accountName(vatDebitAccount)
          .amount(vatAmt)
          .description(itemName + " 부가세")
          .sortOrder(sortOrder++)
          .build());
      } else {
        // 부가세 계정 미설정 시: 전체 금액을 단일 차변으로 (차변 = 대변 = totalAmt, 균형 유지)
        log.warn("선급 부가세 차변 계정(advanceVatMapping.debit) 미설정으로 전체 금액을 단일 차변으로 처리합니다. itemName={}", itemName);
        voucher.addLine(VoucherLine.builder()
          .lineType("DEBIT")
          .accountName(debitAccount)
          .amount(totalAmt)
          .description(itemName)
          .sortOrder(sortOrder++)
          .build());
      }
    } else {
      // 면세/비과세 항목 (취득세, 인지대 등): 단일 차변
      voucher.addLine(VoucherLine.builder()
        .lineType("DEBIT")
        .accountName(debitAccount)
        .amount(totalAmt)
        .description(itemName)
        .sortOrder(sortOrder++)
        .build());
    }

    voucher.addLine(VoucherLine.builder()
      .lineType("CREDIT")
      .accountName(creditAccount)
      .amount(totalAmt)
      .description(paymentMethod)
      .sortOrder(sortOrder)
      .build());

    voucherRepo.save(voucher);
  }

  private void deleteAutoGeneratedVouchers(VehicleOrder order) {
    String memoPrefix = autoVoucherMemoPrefix(order);
    List<Voucher> oldVouchers = voucherRepo.findByMemoStartingWithOrderByIdAsc(memoPrefix);
    if (!oldVouchers.isEmpty()) {
      voucherRepo.deleteAll(oldVouchers);
    }
  }

  // 자동전표 메모 접두 = 프리픽스 + 차량관리번호 + (#행PK).
  // 발주(미실행) …000은 N행이 공유하므로 행 PK로 구분해야 형제행 전표가 잘못 삭제되지 않는다.
  private String autoVoucherMemoPrefix(VehicleOrder order) {
    return AUTO_VOUCHER_MEMO_PREFIX + order.getVehicleMgmtNo() + " (#" + order.getId() + ")";
  }

  private String mapItemNameToDebitAccount(String itemName) {
    if (itemName == null || itemName.isBlank()) {
      throw new RuntimeException("항목명이 없습니다.");
    }
    // 기타계정관리 설정에서 항목명에 맞는 계정명 조회
    String fromSettings = accountSettings.getPrepaidDebitAccount(itemName);
    if (fromSettings != null) return fromSettings;
    // 설정에 없으면 기본값
    return "차량운반구";
  }

  private String mapPaymentMethodToCreditAccount(String paymentMethod) {
    if (paymentMethod == null || paymentMethod.isBlank()) {
      throw new RuntimeException("지급방법이 결정되지 않은건이 있습니다.");
    }
    // BUG-10차-02: 하드코딩된 계정명("보통예금" 등)이 재무상태표 보통예금 음수 유발.
    // 기타계정관리 vehicleMapping.credit 설정값을 우선 사용한다.
    // 설정이 없을 경우에만 지급방법별 기본값으로 fallback.
    String creditFromSettings = accountSettings.getVehicleCreditAccount();
    if (creditFromSettings != null) {
      return creditFromSettings;
    }
    return switch (paymentMethod) {
      case "미지급금" -> "미지급금";
      case "법인카드" -> "미지급비용";
      case "보통예금" -> "보통예금";
      default -> throw new RuntimeException("지원하지 않는 지급방법입니다: " + paymentMethod);
    };
  }

  private String generateVoucherNo(LocalDate voucherDate) {
    return voucherNumberService.next(voucherDate);
  }

  private long nvl(Long v) {
    return v == null ? 0L : v;
  }

  private String nvlStr(String s) {
    return s == null ? "" : s;
  }

  private String emptyToNull(String s) {
    return (s == null || s.isBlank()) ? null : s;
  }
}